import "./globals.css";
import { Amarante, Geist, Geist_Mono } from "next/font/google";
import QueryProvider from "./query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const amarante = Amarante({
  weight: "400",
  subsets: ["latin"], // ✅ required
  display: "auto",
  variable: "--font-amarante",
});

export const metadata = {
  title: "Ealaami Interior Solutions",
  description: "Generated by create next app",
  icons: {
    icon: "/images/titleLogo.jpg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${amarante.variable}`}
    >
      <body className="antialiased">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
